# Generated by Django 4.2.5 on 2023-12-14 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranthubapp', '0003_alter_room_options_room_partipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='partipants',
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
